### ISSUE TITLE
Improving the docs

### ISSUE THREAD

**Issue by idavidmcdonald** [camptocamp/terraform-provider-pass#11]
Hi 👋 

I just started using the provider (thanks!). I was looking at opening at PR that adds further documentation for the resources and data sources so it matches the Terraform docs more closely (e.g. listing the arguments and attributes for data sources and resources). This would have made things a little bit quicker for me as I ended up looking into the code to find that info originally. 

I'm happy to put in a PR if you think this would be useful?

Thanks

**Comment by mcanevet** [comment]
@idavidmcdonald any help is always welcome

**Comment by idavidmcdonald** [comment]
It took me a little while but here we go - https://github.com/camptocamp/terraform-provider-pass/pull/14

**Comment by mcanevet** [comment]
Fixed by #14
