### ISSUE TITLE
Windows x64 compile

### ISSUE THREAD

**Issue by standardizer** [camptocamp/terraform-provider-pass#19]
There is a compiled release for x64 Linux for download here. Could anyone add x64 Windows compiles to the release process, please?
If not: Could anyone provide a current Windows x64 build?

Thank you very much,
ms

**Comment by phillipj** [comment]
Having macOS binaries would also be very handy. Assuming this could be accomplished with go's cross compilation features? Something in the lines of:

```
$ GOOS=linux GOARCH=amd64 go build -o binaries/terraform-provider-pass-linux-amd64
$ GOOS=darwin GOARCH=amd64 go build -o binaries/terraform-provider-pass-darwin-amd64
$ GOOS=windows GOARCH=386 go build -o binaries/terraform-provider-pass-windows-386.exe
```

@cryptobioz any thoughts?

**Comment by cryptobioz** [comment]
You're right, I'll try to compile these binaries and publish them as soon as possible.

**Comment by phillipj** [comment]
Thanks a bunch for the lightning quick response!

**Comment by cryptobioz** [comment]
The binaries are now available for the latest release: https://github.com/camptocamp/terraform-provider-pass/releases/tag/1.2.1.

**Comment by phillipj** [comment]
Fantastic! @standardizer assuming this issue can be closed?
