### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by michel-kraemer** [camptocamp/terraform-provider-pass#2]
I cannot build the provider. I tried it with the instructions from the README and also with

    go get github.com/camptocamp/terraform-provider-pass

but I get the following error:

```
# github.com/camptocamp/terraform-provider-pass/pass
src/github.com/camptocamp/terraform-provider-pass/pass/provider.go:49:19: multiple-value action.New() in single-value context
src/github.com/camptocamp/terraform-provider-pass/pass/provider.go:49:54: cannot use "github.com/blang/semver".Version literal (type "github.com/blang/semver".Version) as type "github.com/justwatchcom/gopass/vendor/github.com/blang/semver".Version in argument to action.New
```

Any idea how to proceed?

**Comment by raphink** [comment]
#3 fixes the first issue.

As per https://github.com/justwatchcom/gopass/issues/532#issuecomment-352659947, the second issue will require vendoring dependencies.
