### ISSUE TITLE
[Question] does this provider prevent secrets from leaking into Terraform's statefile?

### ISSUE THREAD

**Issue by ketzacoatl** [camptocamp/terraform-provider-pass#26]
With this provider, when reviewing the docs and project, it is unclear: Are secrets going into the Terraform statefile? I would be happy to make a PR to the README that clarifies this, but maybe a dev can confirm what is expected behavior?

**Comment by beddari** [comment]
I am not affiliated with this project but recommend first reading https://www.terraform.io/docs/state/sensitive-data.html
and then this excerpt from the Vault docs:

_Currently Terraform has no mechanism to redact or protect secrets that are returned via data sources, so secrets read via this provider will be persisted into the Terraform state, into any plan files, and in some cases in the console output produced while planning and applying. These artifacts must therefore all be protected accordingly._

**Comment by yann-soubeyrand** [comment]
I confirm that this provider doesn’t prevent sensitive values from leaking in the statefile if not otherwise handled by the resource providers (some providers do not store sensitive attributes in the statefile or store them encrypted if you provide a GPG key).
