### ISSUE TITLE
[BUGFIX] Return err on ResourceRead failure

### ISSUE THREAD

**Issue by bassco** [camptocamp/terraform-provider-pass#29]
#28 Fixes error when gpg file is not found or cannot be decoded. Fixes the erroneous error message detailed below.

If a gpg file is not found in the store, then terraform fails with

```sh
* pass_password.my_keyid: pass_password.my_keyid: connection is shut down

terraform plan failed (rc=1). Please fix the error reported and try again.
```
This occured when a secret is referenced multiple times in terraform resources that are being deleted. The first occurrence deletes the referenced secret from the store and subsequent reads fail. 

Perhaps the course of action is not fail silently on deletes and reads in this scenario. 

Or, to create a provider config variable to warn on deletes and not delete from the store.

**Comment by mcanevet** [comment]
Fixed by #28
