### ISSUE TITLE
Publish to Terraform Provider Registry

### ISSUE THREAD

**Issue by mtneug** [camptocamp/terraform-provider-pass#34]
Terraform 0.13 will support to automatically download community provider that are published to the Terraform Provider Registry. It would be great if the `pass` provider would also be published there.

**Comment by jzielke84** [comment]
I couldn't even manage to get the plugin running due to namespace requirements in the latest terraform version. Using hte registry would be so much easier.

**Comment by jaceq** [comment]
It's already there: https://registry.terraform.io/providers/camptocamp/pass/latest

I guess this can be closed now.
