### ISSUE TITLE
404 on registry.terraform.io/camptocamp/pass

### ISSUE THREAD

**Issue by danylohetmantsev** [camptocamp/terraform-provider-pass#37]
Trying to initialize terraform 0.13 with this provider in source - terraform gives 404.

**Comment by debojitkakoti** [comment]
Facing the same issue

**Comment by raphink** [comment]
I've released 1.4.0, which shouldn't have this issue.

**Comment by danylohetmantsev** [comment]
Approving that it works, thanks!
