### ISSUE TITLE
provider does not work if user updated to gopass 1.10

### ISSUE THREAD

**Issue by jaceq** [camptocamp/terraform-provider-pass#41]
Gopass 1.10 has changed structure of config file. 
This plugin is crashing when a config is from version 1.10.

I guess easiest way would to update gopass dependency here.

To reproduce:
initialize new config with gopass 1.10
try to interact with it

**Comment by toabi** [comment]
I had a closer look into it (I'm not a Go-Expert though)… but with gopass 1.10 a lot of the API this provider uses is now "internal". Here are some spots:

	pass/provider.go:12:2: use of internal package github.com/gopasspw/gopass/internal/action not allowed
	pass/provider.go:13:2: use of internal package github.com/gopasspw/gopass/internal/backend/storage not allowed
	pass/provider.go:14:2: use of internal package github.com/gopasspw/gopass/internal/config not allowed
	pass/provider.go:6:2: use of internal package github.com/gopasspw/gopass/internal/store/root not allowed

So there's probably quite some refactoring work to do to update it for gopass 1.10+

**Comment by jaceq** [comment]
Yes, in fact it seem like a bigger change / major re-write but we're a bit forced to use old version :(

**Comment by toabi** [comment]
We started to work to upgrade this provider for gopass 1.10+

**Comment by jaceq** [comment]
Version 2.0 does! :)
