### ISSUE TITLE
refresh_store = true breaks in some circumstances

### ISSUE THREAD

**Issue by jaceq** [camptocamp/terraform-provider-pass#42]
So refresh_store = true breaks if following conditions are met:
-> store_dir isn't defined
-> root store has no remote git
-> substore / mount has remote git (and I'd like to have it refreshed)

if I define refresh_store = false, this works and I can fetch passwords from substore by simply adding <store_name>/ as a prefix to path.
It would be cool if either refresh_store would refresh all stores (just like gopass sync does) or it would take an argument with store name and refresh this one.

**Comment by mcanevet** [comment]
@raphink I also experience this issue when the main password store has no remote. For example when initialized with just `gopass init`.

**Comment by jaceq** [comment]
Given there is no refresh in the new version closing this now.
