### ISSUE TITLE
terraform 0.13 provider changes & terraform registry

### ISSUE THREAD

**Issue by Phil1602** [camptocamp/terraform-provider-pass#44]
Hi,

thanks for the useful terraform provider.

Since terraform 0.13 the mechanism for third-party has been changed.
Furthermore terraform providers can now be pulled from a registry (https://registry.terraform.io/).

So to fix this issue it would be nice to either have the README updated according to the installation of third-party plugins within terraform 0.13 (see https://www.hashicorp.com/blog/automatic-installation-of-third-party-providers-with-terraform-0-13) or even better, push the pass provider into the global terraform registry.

Thanks,
Philipp

**Comment by mcanevet** [comment]
It is : https://registry.terraform.io/providers/camptocamp/pass/latest
