### ISSUE TITLE
2.0.0 is sorting lines in full attribute

### ISSUE THREAD

**Issue by jakubgs** [camptocamp/terraform-provider-pass#53]
# Description

I recently upgraded to `2.0.0` from `1.4.0` which broke my Google provider, because it appears that `2.0.0` is sorting `full` attribute lines for no good reason.

# Reproducing

Here's a test Terraform module:
```Terraform
data "pass_password" "debug" {
  path = "test-json-entry"
}
output "debug" {
  value = data.pass_password.debug.full
}
```
Where `test-json-entry` is an entry in `pass` that consists of:
```json
{
  "B": "b",
  "C": "c",
  "A": "a"
}
```
With `1.4.0` installed this is the output:
```
 > terraform output
debug = <<EOT
{
  "B": "b",
  "C": "c",
  "A": "a"
}

EOT
```
But with `2.0.0` it looks like this:
```
 > terraform output
debug = <<EOT
{
"A": "a"
"B": "b",
"C": "c",
}

EOT
```
As seen, the lines are sorted in a way that breaks JSON because of the missing trailing comma.
This was tested on Terraform `v0.14.4`.

**Comment by arthurk** [comment]
I believe this is because gopass is parsing the content. I can reproduce the above issue with gopass 1.12.5. The JSON content is parsed, sorted and then output without indentation. It works fine when passing the `--noparsing` option to gopass which will disable parsing the content.

It would be great to have a `noparsing` option on the tf resource/data source where we can disable parsing.

**Comment by jakubgs** [comment]
Good catch. And it appears that `gopass` provides a `WithShowParsing()` context function:
```go
// WithShowParsing returns a context with the value for ShowParsing set
func WithShowParsing(ctx context.Context, bv bool) context.Context {
	return context.WithValue(ctx, ctxKeyShowParsing, bv)
}
```
https://github.com/gopasspw/gopass/blob/d00c29a0e8e521eb32e4564998690430dcc7dbbc/pkg/ctxutil/ctxutil.go#L171-L174

**Comment by jakubgs** [comment]
It should be as simple as adjusting the context here, when creating an instance of `gopass` API:
https://github.com/camptocamp/terraform-provider-pass/blob/49c83e5b924b1bee8569b1f0ce241a335f1a9067/pass/provider.go#L29-L32

**Comment by jakubgs** [comment]
Simplest possible fix: https://github.com/camptocamp/terraform-provider-pass/pull/54
