### ISSUE TITLE
Arm64 (Apple Silicon) support

### ISSUE THREAD

**Issue by ErwinSteffens** [camptocamp/terraform-provider-pass#57]
Hi everybody,

Is this project still alive? Not seeing much activity here lately. 

I would love to see this project updated to support running the plugin on arm64 (Apple Silicon). I can help out with this if needed, but I am not much of a golang expert.

**Comment by toabi** [comment]
As this project has not much activity anymore I took this in my own hands and forked, updated and released this provider: https://github.com/mecodia/terraform-provider-pass

**Comment by yann-soubeyrand** [comment]
I think this issue is fixed now.
